version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # ou a versão que você precisar
    commands:
      - echo Iniciando a fase de instalação
      - npm install
  pre_build:
    commands:
      - echo Iniciando a fase de pré-construção
      - docker-compose --version
      - docker --version
  build:
    commands:
      - echo Iniciando a fase de construção
      - docker-compose up -d --build
  post_build:
    commands:
      - echo Iniciando a fase de pós-construção
      - docker-compose ps
      - aws elasticbeanstalk update-environment --application-name "crud-git" --version-label "versao_nova" --environment-name "Crud-git-env"

artifacts:
  files:
    - "**/*"

cache:
  paths:
    - node_modules/**/*
